"""Refactor weather model

Revision ID: 0e79409077c9
Revises: 
Create Date: 2025-05-12 17:39:31.465137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e79409077c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('air_quality_carbon_monoxide', sa.Float(), nullable=True),
    sa.Column('air_quality_ozone', sa.Float(), nullable=True),
    sa.Column('air_quality_nitrogen_dioxide', sa.Float(), nullable=True),
    sa.Column('air_quality_sulphur_dioxide', sa.Float(), nullable=True),
    sa.Column('air_quality_pm2_5', sa.Float(), nullable=True),
    sa.Column('air_quality_pm10', sa.Float(), nullable=True),
    sa.Column('air_quality_us_epa_index', sa.Integer(), nullable=True),
    sa.Column('air_quality_gb_defra_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_mph', sa.Float(), nullable=False),
    sa.Column('gust_kph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='wind_direction'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.Time(), nullable=False),
    sa.Column('wind_id', sa.Integer(), nullable=True),
    sa.Column('air_quality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['air_quality_id'], ['air_quality.id'], ),
    sa.ForeignKeyConstraint(['wind_id'], ['wind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('wind')
    op.drop_table('air_quality')
    # ### end Alembic commands ###
