"""Add should_go_outside column_fix

Revision ID: 1a5a2c69797e
Revises: 0e79409077c9
Create Date: 2025-05-12 18:03:53.521698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5a2c69797e'
down_revision: Union[str, None] = '0e79409077c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wind', sa.Column('should_go_outside', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wind', 'should_go_outside')
    # ### end Alembic commands ###
